# This workflow will periodically run every 15 minutes and send a webhook notification to the Discord server for meetings starting in the next 20 minutes.

name: Send Meeting Reminders

on:
  workflow_dispatch:
  schedule:
    # Run workflow every 20 minutes
    - cron: "*/20 * * * *"

jobs:
  send_reminders:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install
    - name: Rune script
      run: pipenv run python scripts/meeting_reminders.py
